# Generated by Django 4.2.3 on 2023-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ignore',
            field=models.BooleanField(default=False, help_text='Игнор', verbose_name='Игнор'),
        ),
    ]
