# Generated by Django 4.2.3 on 2023-07-24 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_users_ignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1_timer', models.DateTimeField(default=datetime.datetime(2023, 7, 24, 12, 16, 48, 3226), help_text='Таймер на 10 минут', verbose_name='Когда отправляем уведомление')),
                ('owner', models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_timer', to='admin_panel.users', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressed_sub_button', models.BooleanField(default=False, help_text='Нажата кнопка "Я подписалась"', verbose_name='Нажата кнопка "Я подписалась"')),
                ('owner', models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='admin_panel.users', verbose_name='Пользователь')),
            ],
        ),
    ]
