# Generated by Django 4.2.3 on 2023-07-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_timer_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='s1_timer',
            field=models.DateTimeField(help_text='Таймер на 10 минут', null=True, verbose_name='Когда отправляем уведомление'),
        ),
    ]
