# Generated by Django 4.2.3 on 2023-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_timer_s1_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='s1_send',
            field=models.BooleanField(default=False, help_text='Да/нет', verbose_name='Отправили напоминание через 10 минут?'),
        ),
    ]
