# Generated by Django 4.2.3 on 2023-07-24 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_users_created_users_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='b4_send',
            field=models.BooleanField(default=False, verbose_name='Отправили напоминание через 5 минут?'),
        ),
        migrations.AddField(
            model_name='timer',
            name='b4_timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 12, 2, 55, 87054, tzinfo=datetime.timezone.utc), help_text='Таймер на 5 минут', verbose_name='Таймер B4'),
        ),
    ]
