# Generated by Django 4.2.3 on 2023-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_timer_b4_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='amount_refferal',
            field=models.IntegerField(default=0, help_text='Кол-во приглашенных', verbose_name='Кол-во приглашенных'),
        ),
    ]
