# Generated by Django 4.2.3 on 2023-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_users_amount_refferal'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='ref_send',
            field=models.BooleanField(default=False, help_text='Отправили напоминание рефералки', verbose_name='Отправили напоминание рефералки'),
        ),
        migrations.AddField(
            model_name='timer',
            name='ref_timer',
            field=models.DateTimeField(help_text='Таймер рефералки', null=True, verbose_name='Таймер рефералки'),
        ),
    ]
