# Generated by Django 4.2.3 on 2023-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_timer_ref_send_timer_ref_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='ref2_send',
            field=models.BooleanField(help_text='Отправили вторую напоминалку', null=True, verbose_name='Отправили вторую напоминалку'),
        ),
        migrations.AddField(
            model_name='timer',
            name='ref2_timer',
            field=models.DateTimeField(help_text='2й таймер рефералки', null=True, verbose_name='2й таймер рефералки'),
        ),
    ]
