# Generated by Django 4.2.3 on 2023-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_timer_ref2_send_timer_ref2_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='got_tasks',
            field=models.BooleanField(default=False, help_text='Получила комплекс упражнений', verbose_name='Получила комплекс упражнений'),
        ),
    ]
