# Generated by Django 4.2.3 on 2023-07-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_statistic_got_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('subscriber', models.ForeignKey(blank=True, help_text='Подписчик', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sub', to='admin_panel.users', verbose_name='Подписчик')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
