# Generated by Django 4.2.3 on 2023-07-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_subchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchannel',
            name='check_date',
            field=models.DateTimeField(null=True),
        ),
    ]
