# Generated by Django 4.2.3 on 2023-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_subchannel_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchannel',
            name='updated_date',
            field=models.BooleanField(default=False),
        ),
    ]
