# Generated by Django 4.2.3 on 2023-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_subchannel_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='got_poll',
            field=models.BooleanField(default=False, help_text='Получила сообщение с анкетой', verbose_name='Получила сообщение с анкетой'),
        ),
    ]
