# Generated by Django 4.2.3 on 2023-07-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_statistic_got_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('question_1', models.CharField(help_text='Ответ на первый вопрос', max_length=10000, null=True, verbose_name='Ответ на первый вопрос')),
                ('question_2', models.CharField(help_text='Ответ на второй вопрос', max_length=10000, null=True, verbose_name='Ответ на второй вопрос')),
                ('question_3', models.CharField(help_text='Ответ на третий вопрос', max_length=10000, null=True, verbose_name='Ответ на третий вопрос')),
                ('question_4', models.CharField(help_text='Ответ на четвертый вопрос', max_length=10000, null=True, verbose_name='Ответ на четвертый вопрос')),
                ('question_5', models.CharField(help_text='Ответ на пятый вопрос', max_length=10000, null=True, verbose_name='Ответ на пятый вопрос')),
                ('question_6', models.CharField(help_text='Ответ на шестой вопрос', max_length=10000, null=True, verbose_name='Ответ на шестой вопрос')),
                ('question_7', models.CharField(help_text='Ответ на седьмой вопрос', max_length=10000, null=True, verbose_name='Ответ на седьмой вопрос')),
                ('question_8', models.CharField(help_text='Ответ на восьмой вопрос', max_length=10000, null=True, verbose_name='Ответ на восьмой вопрос')),
                ('question_9', models.CharField(help_text='Ответ на девятый вопрос', max_length=10000, null=True, verbose_name='Ответ на девятый вопрос')),
                ('owner', models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poll', to='admin_panel.users', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
