# Generated by Django 4.2.3 on 2023-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='finish_poll',
            field=models.BooleanField(default=False, help_text='Прошла опрос', verbose_name='Прошла опрос'),
        ),
    ]
