# Generated by Django 4.2.3 on 2023-07-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_statistic_finish_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='question_9',
        ),
    ]
