# Generated by Django 4.2.3 on 2023-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_remove_poll_question_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='b5_send',
            field=models.BooleanField(default=False, verbose_name='Отправили напоминание через 48 часов?'),
        ),
        migrations.AddField(
            model_name='timer',
            name='b5_timer',
            field=models.DateTimeField(help_text='Таймер на 48 часов', null=True, verbose_name='Таймер B4'),
        ),
    ]
