# Generated by Django 4.2.3 on 2023-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_timer_b5_send_timer_b5_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='sub_club',
            field=models.BooleanField(default=False, help_text='Подписалась ли на клуб', verbose_name='Подписалась ли на клуб'),
        ),
    ]
