# Generated by Django 4.2.3 on 2023-07-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_statistic_sub_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='send_trip',
            field=models.BooleanField(default=False, help_text='Отправили трипваер', verbose_name='Отправили трипваер'),
        ),
    ]
